name: CI - Auth Service

on:
  push:
    paths:
      - 'backend/backend/auth-service/**'
      - '.github/workflows/auth-service.yml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: auth-service
      service_path: backend/backend/auth-service
