name: CI - Customer Service

on:
  push:
    paths:
      - 'backend/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: customer-service
      service_path: backend/customer-service
