name: Deploy - Order Service

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: order-service
      service_path: backend/backend/order-service
    secrets: inherit
