name: Deploy - Auth Service

on:
  workflow_run:
    workflows: ["CI - Auth Service"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: auth-service
      service_path: backend/backend/auth-service
