name: Deploy - Inventory Consumer

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: inventory-consumer
      service_path: backend/backend/inventory-consumer
    secrets: inherit
