name: Deploy - Payment Service

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: payment-service
      service_path: backend/payment-service
    secrets: inherit
