name: Deploy - Inventory Consumer (Inventory Service)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: inventory-service
      service_path: backend/inventory-service
    secrets: inherit
