name: Deploy - Auth Service

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-backend-deploy.yml
    with:
      service_name: authentication-service
      service_path: backend/authentication-service
    secrets: inherit
