name: CI - Email Consumer

on:
  push:
    paths:
      - 'backend/email-consumer/**'
      - '.github/workflows/email-consumer.yml'
    branches:
      - ci-cd
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: email-consumer
      service_path: backend/email-consumer
    secrets: inherit
