name: CI - Payment Service

on:
  push:
    paths:
      - 'backend/backend/payment-service/**'
      - '.github/workflows/payment-service.yml'
      - '.github/workflows/deploy-payment.yml'
    branches:
      - ci-cd
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: payment-service
      service_path: backend/backend/payment-service

  trigger_cd:
    needs: ci
    if: github.ref == 'refs/heads/ci-cd' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-payment.yml
    secrets: inherit
