name: CI - Product Service

on:
  push:
    paths:
      - 'backend/product-service/**'
      - '.github/workflows/product-service.yml'
    branches:
      - ci-cd
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: product-service
      service_path: backend/product-service
    secrets: inherit
