name: Reusable Backend Deploy

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Install dependencies and Zip
        working-directory: ${{ inputs.service_path }}
        run: |
          npm ci --production
          zip -r function.zip . -x "*.git*" -x "*tests*"
        
      - name: Deploy Service to Lambda
        working-directory: ${{ inputs.service_path }}
        run: |
          FUNCTION_NAME="euphoriax-${{ inputs.service_name }}"
          aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip
