name: CI - User Service

on:
  push:
    paths:
      - 'backend/backend/user-service/**'
      - '.github/workflows/user-service.yml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service_name: user-service
      service_path: backend/backend/user-service
